### ISSUE TITLE
** (ArgumentError) invalid syntax, only "retry", "after" and "else" are permitted

### ISSUE THREAD

**Issue by simonbowen** [fredwu/crawler#18]
It seems as though by updating the ElixirRetry package it has introduced an issue. I cannot add this project to my mix.exs and run 

`iex -S mix`

without receiving this error

```
== Compilation error in file lib/crawler/fetcher/retrier.ex ==
** (ArgumentError) invalid syntax, only "retry", "after" and "else" are permitted
    expanding macro: Retry.retry/2
    lib/crawler/fetcher/retrier.ex:25: Crawler.Fetcher.Retrier.perform/2
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by fredwu** [comment]
This is already fixed in fedd5a0c27b345d1db5061304c9b7fdcdfea887c. If you are using the released version you can lock ElixirRetry to v0.9. :)

**Comment by cerdiogenes** [comment]
@fredwu I don't understand your instructions. I tried to add {:retry, "0.9.0"} and {:retry, "0.9.1"}, but still getting the same error. Can you give more direct instructions? Thanks!

**Comment by cerdiogenes** [comment]
I used `{:crawler, github: "fredwu/crawler"}` and now it's compile successful.
